package com.skillguard;

import java.util.Arrays;
import java.util.List;

public final class BuiltinRules {
    private BuiltinRules() {
    }

    public static List<Rule> all() {
        return Arrays.asList(
                new Rule("FILE001", "sensitive_file_access", Severity.CRITICAL,
                        "(~[/\\\\])?\\.ssh[/\\\\]|id_rsa|id_ed25519|\\.aws[/\\\\]credentials|\\.azure[/\\\\]|credentials\\.json|secrets?\\.(json|ya?ml|env)|(?:^|[/\\\\])\\.env\\b|(?:^|[/\\\\])[^\\s\\\"']+\\.(pem|key)\\b|(open|read|load|cat|get-content)[^\\n]{0,80}[\\\"'][^\\\"']*(\\.env|\\.pem|\\.key)[\\\"']",
                        "访问或引用敏感本地凭据文件",
                        "避免读取宿主机敏感文件；改为显式传入受控测试配置或使用临时凭据。", 0.9),
                new Rule("FILE002", "workspace_escape", Severity.HIGH,
                        "(\\.\\.[/\\\\]|C:\\\\Users\\\\|/Users/|/home/|/etc/|/var/|Desktop|Downloads).{0,80}(write|open|save|download|extract|unzip|copy|move|delete|Remove-Item|写入|保存|下载|解压|复制|移动|删除)|(write|open|save|download|extract|unzip|copy|move|delete|Remove-Item|写入|保存|下载|解压|复制|移动|删除).{0,80}(\\.\\.[/\\\\]|C:\\\\Users\\\\|/Users/|/home/|/etc/|/var/|Desktop|Downloads)",
                        "文件操作可能越出当前工作区",
                        "文件读写、下载和解压应限制在当前 Skill 工作目录或受控临时目录，禁止默认写入用户目录、系统目录或任意相对上级路径。", 0.82),
                new Rule("EXFIL001", "data_exfiltration", Severity.CRITICAL,
                        "(curl|wget|requests\\.(post|put)|httpx\\.(post|put)|fetch\\().*(-d|--data|@|token|secret|password|\\.env|\\.ssh)",
                        "疑似把敏感数据通过网络发送出去",
                        "外联前应列出目的域名、数据字段和脱敏策略，并在隔离环境验证。", 0.95),
                new Rule("NET001", "external_network", Severity.HIGH,
                        "\\b(curl|wget)\\b\\s+.*https?://|requests\\.(get|post|put|delete)\\(|httpx\\.|urllib\\.|fetch\\(",
                        "存在外部网络请求能力",
                        "将允许访问的域名写入审计说明，测试环境中建议使用 mock 服务。", 0.75),
                new Rule("NET002", "ssrf_or_internal_network", Severity.HIGH,
                        "(169\\.254\\.169\\.254|metadata\\.google|metadata\\.azure|localhost|127\\.0\\.0\\.1|0\\.0\\.0\\.0|10\\.\\d+\\.\\d+\\.\\d+|172\\.(1[6-9]|2\\d|3[0-1])\\.\\d+\\.\\d+|192\\.168\\.\\d+\\.\\d+|internal|intranet|内网|元数据|metadata).{0,120}(curl|wget|requests\\.|httpx\\.|fetch\\(|urllib\\.|url|endpoint|api)|(curl|wget|requests\\.|httpx\\.|fetch\\(|urllib\\.|url|endpoint|api).{0,120}(169\\.254\\.169\\.254|metadata\\.google|metadata\\.azure|localhost|127\\.0\\.0\\.1|0\\.0\\.0\\.0|10\\.\\d+\\.\\d+\\.\\d+|172\\.(1[6-9]|2\\d|3[0-1])\\.\\d+\\.\\d+|192\\.168\\.\\d+\\.\\d+|internal|intranet|内网|元数据|metadata)",
                        "疑似访问内网、localhost 或云元数据地址",
                        "禁止把用户可控 URL 或测试脚本直接打到内网、localhost、云元数据服务；需要域名白名单、私网地址拦截和沙箱隔离。", 0.84),
                new Rule("CMD001", "dangerous_command", Severity.CRITICAL,
                        "\\bsudo\\b|\\bsu\\s|rm\\s+-rf\\s+[/~]|chmod\\s+(777|a\\+rwx)|\\bdd\\s+.*of=/|>\\s*/(etc|usr|bin|sbin)/",
                        "存在高危系统命令或危险文件写入",
                        "移除破坏性命令；如确需清理，只允许操作明确的临时工作目录。", 0.9),
                new Rule("CMD002", "shell_execution", Severity.HIGH,
                        "os\\.system\\s*\\(|subprocess\\.(run|call|popen|Popen).*shell\\s*=\\s*True|child_process\\.exec\\s*\\(|Runtime\\.getRuntime\\(\\)\\.exec",
                        "存在系统命令执行能力",
                        "优先使用参数化 API，禁止拼接用户输入执行 shell。", 0.82),
                new Rule("INJ001", "dynamic_code_execution", Severity.HIGH,
                        "\\beval\\s*\\(|\\bexec\\s*\\(|__import__\\s*\\(|new\\s+Function\\s*\\(|Function\\s*\\(",
                        "存在动态代码执行或动态导入",
                        "避免执行动态生成代码；必要时增加来源校验和最小权限隔离。", 0.8),
                new Rule("OBF001", "obfuscation", Severity.MEDIUM,
                        "base64\\.(b64decode|decode)|atob\\s*\\(|fromCharCode|chr\\s*\\(.+\\)\\s*\\+\\s*chr|getattr\\s*\\(",
                        "存在混淆或间接调用特征",
                        "将隐藏逻辑改为可审计的显式实现，并补充说明用途。", 0.7),
                new Rule("DEP001", "dependency_pollution", Severity.HIGH,
                        "npm\\s+(install|i).*\\s-g\\b|yarn\\s+global|pip\\s+install.*(--user|--break-system-packages)|gem\\s+install",
                        "存在全局依赖安装，可能污染开发或测试环境",
                        "使用项目本地虚拟环境、锁文件和可复现安装命令。", 0.85),
                new Rule("DEP002", "dependency_override", Severity.MEDIUM,
                        "pip\\s+install.*(--upgrade|--force-reinstall|--ignore-installed)|npm\\s+install.*--force",
                        "存在强制升级或覆盖依赖",
                        "在隔离环境验证依赖变更，避免修改全局或共享测试环境。", 0.78),
                new Rule("TEST001", "test_artifact_deletion", Severity.HIGH,
                        "rm\\s+-rf\\s+.*(allure-results|allure-report|test-results|coverage|reports?|screenshots?|traces?)|Remove-Item\\s+.*(allure-results|test-results|coverage|reports?)",
                        "可能删除测试报告、覆盖率或调试产物",
                        "清理操作应限制在当前 skill 的临时目录，并保留失败现场。", 0.86),
                new Rule("TEST002", "ci_mutation", Severity.HIGH,
                        "\\.github[/\\\\]workflows|\\.gitlab-ci\\.ya?ml|Jenkinsfile|azure-pipelines\\.ya?ml|circleci[/\\\\]config\\.ya?ml",
                        "访问或修改 CI/CD 配置",
                        "Skill 不应静默修改流水线；变更必须进入代码评审。", 0.75),
                new Rule("TEST003", "test_secret_fixture", Severity.CRITICAL,
                        "((fixtures?|testdata|mock-data|测试数据)[/\\\\].*(secret|password|token|api[_-]?key|credential))|((fixtures?|testdata|mock-data|测试数据).*(secret|password|token|api[_-]?key|credential)\\s*(=|:))",
                        "测试数据或 fixture 中疑似包含密钥",
                        "测试数据需要脱敏；密钥应使用专门的测试凭据注入。", 0.9),
                new Rule("TEST004", "load_test_risk", Severity.MEDIUM,
                        "(while\\s+true|for\\s*\\(;;\\)|repeat\\s*\\().*(curl|requests\\.|fetch\\()|\\b(ab|wrk|hey|siege|jmeter)\\b",
                        "存在压测或无限请求风险",
                        "压测必须限制目标、并发、持续时间和速率，并默认指向测试环境。", 0.76),
                new Rule("TEST005", "browser_profile_access", Severity.HIGH,
                        "(chrome|chromium|edge|firefox).*(profile|cookies?|localstorage|user data)|Cookies[/\\\\]|Local Storage[/\\\\]",
                        "可能读取浏览器 profile、cookie 或 localStorage",
                        "浏览器自动化应使用临时 profile，禁止读取真实用户会话数据。", 0.88),
                new Rule("NORM-GEN001", "norm_general_security", Severity.HIGH,
                        "(debugger|mock\\s*=\\s*true|enableDebug|debug\\s*mode|测试页面|调试页面|后门|backdoor|逻辑炸弹|logic\\s*bomb)",
                        "行内规范：疑似调试、Mock、后门或逻辑炸弹相关能力",
                        "上线或共享前必须移除调试入口、Mock 开关、后门逻辑和条件触发破坏逻辑。", 0.78),
                new Rule("BANK001", "production_environment", Severity.CRITICAL,
                        "(prod|production|生产环境|真实环境|真实库|核心库|core[-_ ]?bank|柜面|账务|清算|支付).*(host|url|jdbc|endpoint|账号|密码|token|密钥)|jdbc:.*(prod|生产|core)",
                        "疑似引用银行生产环境或核心系统连接信息",
                        "Skill 不应内置生产环境地址、账号或核心系统连接信息；必须通过受控配置和审批流程注入。", 0.92),
                new Rule("BANK002", "financial_pii", Severity.CRITICAL,
                        "(身份证|证件号|银行卡|卡号|手机号|客户号|账户号|accountNo|cardNo|idCard|mobile).*(=|:|\\s).{4,}",
                        "疑似包含客户敏感信息或金融个人信息",
                        "测试数据必须脱敏或合成；禁止在 Skill、fixture、日志样例中保留真实客户数据。", 0.88),
                new Rule("BANK003", "database_destructive_operation", Severity.CRITICAL,
                        "\\b(drop|truncate|delete)\\s+(table\\s+)?(customer|account|card|loan|payment|transaction|user|客户|账户|交易)|update\\s+.*set\\s+.*(balance|余额|amount|金额)",
                        "疑似包含高危数据库变更或账务数据修改",
                        "数据库操作应只面向隔离测试库，并要求事务回滚、审批和最小权限账号。", 0.9),
                new Rule("BANK004", "privacy_logging", Severity.HIGH,
                        "(print|console\\.log|logger\\.|log\\.info|System\\.out\\.println).*(password|secret|身份证|银行卡|手机号|accountNo|cardNo|auth[_-]?token|access[_-]?token|refresh[_-]?token|cookie|session)",
                        "日志中可能输出敏感数据",
                        "日志必须脱敏，避免输出凭据、客户号、证件号、卡号和手机号。", 0.82),
                new Rule("BANK005", "user_identifier_exposure", Severity.HIGH,
                        "\"(users?|user[_-]?ids?|operator|柜员|用户)\"\\s*:\\s*(\\[[^\\]]*[0-9]{5,}[^\\]]*\\]|\"[^\"]*[0-9]{5,}[^\"]*\")",
                        "疑似暴露测试用户、柜员号或认证主体信息",
                        "报告和样例中应脱敏用户标识；保留角色类型即可，避免沉淀真实测试账号或柜员号。", 0.84),
                new Rule("AUTH001", "auth_secret_hardcode", Severity.CRITICAL,
                        "(username|user|login|账号|用户名).{0,30}(password|passwd|pwd|密码|otp|验证码|动态口令|mfa).{0,30}(=|:)",
                        "疑似硬编码登录凭据或动态口令",
                        "测试账号、密码、OTP、MFA 种子必须通过受控密钥管理或临时变量注入，禁止写入 Skill。", 0.9),
                new Rule("AUTH002", "session_token_exposure", Severity.CRITICAL,
                        "(Authorization\\s*:\\s*Bearer|Bearer\\s+[A-Za-z0-9._-]{20,}|JSESSIONID|SESSIONID|Set-Cookie|Cookie\\s*:|jwt|access[_-]?token|refresh[_-]?token)",
                        "疑似暴露会话、Cookie 或访问令牌",
                        "Token、Cookie、SessionId 不得进入 Skill、日志、报告或示例数据。", 0.92),
                new Rule("AUTH003", "tls_verification_disabled", Severity.HIGH,
                        "(verify\\s*=\\s*False|rejectUnauthorized\\s*:\\s*false|NODE_TLS_REJECT_UNAUTHORIZED\\s*=\\s*0|curl\\s+.*\\s-k\\b|--insecure|trustAllCerts)",
                        "关闭 TLS/证书校验",
                        "测试环境也应使用受信任证书；确需临时跳过校验必须有隔离环境和审批记录。", 0.86),
                new Rule("AUTH004", "auth_bypass", Severity.CRITICAL,
                        "(skipAuth|disableAuth|bypassAuth|mock\\s+admin|isAdmin\\s*=\\s*true|跳过认证|绕过鉴权|禁用鉴权|免登录)",
                        "疑似绕过认证或鉴权逻辑",
                        "安全测试可以设计越权用例，但执行脚本必须限定测试账号、环境和审批边界。", 0.88),
                new Rule("AUTH005", "privileged_test_account", Severity.HIGH,
                        "(admin|administrator|root|superuser|超级管理员|超级柜员|运维账号|dba|sysdba).{0,30}(password|pwd|token|登录|账号|account)",
                        "疑似使用高权限账号执行测试",
                        "自动化测试应使用最小权限测试账号；高权限账号仅用于受控人工验证。", 0.82),
                new Rule("AUTH006", "crypto_signing_secret", Severity.CRITICAL,
                        "(client[_-]?secret|app[_-]?secret|sign[_-]?key|private[_-]?key|\\bAK\\b|\\bSK\\b|accessKey|secretKey|签名密钥|加签密钥|验签密钥)\\s*(=|:)",
                        "疑似硬编码签名密钥或应用密钥",
                        "签名密钥、AK/SK 和 client_secret 必须由密钥系统注入并做最小权限控制。", 0.9),
                new Rule("NORM-AUTH001", "norm_auth_password_policy", Severity.MEDIUM,
                        "(password|passwd|pwd|密码|口令).{0,30}(admin|test|123456|password|qwerty|默认|初始|弱)|(默认密码|缺省密码|弱口令|初始密码)",
                        "行内规范：疑似弱口令、默认密码或初始密码风险",
                        "认证测试应覆盖弱口令与默认密码限制；Skill 不应沉淀默认密码或弱口令样例。", 0.7),
                new Rule("NORM-SESSION001", "norm_session_cookie_flags", Severity.HIGH,
                        "Set-Cookie(?!.*Secure)|Set-Cookie(?!.*HttpOnly)|Cookie\\s*:.*(JSESSIONID|SESSIONID)",
                        "行内规范：Cookie 或会话标识可能缺少 Secure/HttpOnly 或被写入材料",
                        "会话标识应放在 Cookie 中并设置 Secure、HttpOnly；不得进入 URL、日志、报告或示例。", 0.78),
                new Rule("NORM-SESSION002", "norm_session_lifecycle", Severity.MEDIUM,
                        "(session|会话).*(未超时|永不过期|不失效|永久有效|never\\s*expire)|(修改密码|权限变更).*(不退出|不失效)",
                        "行内规范：会话超时、注销或强制失效机制可能不足",
                        "修改密码、权限变更、注销、多点登录策略应触发现有会话失效。", 0.68),
                new Rule("DATA001", "real_customer_data", Severity.CRITICAL,
                        "(real[_-]?customer|prod[_-]?dump|生产数据|真实客户|原始数据|脱敏前|客户流水|交易流水|账户流水)",
                        "疑似引用真实客户数据或生产数据导出",
                        "测试数据必须使用合成或脱敏数据，禁止将生产导出数据沉淀到 Skill。", 0.88),
                new Rule("DATA002", "bulk_data_export", Severity.HIGH,
                        "(select\\s+\\*\\s+from|mysqldump|expdp|pg_dump|mongoexport|导出).*(customer|account|card|transaction|客户|账户|卡|交易|流水)",
                        "疑似批量导出客户、账户或交易数据",
                        "批量数据导出必须审批、脱敏并限制字段范围；Skill 默认不应具备该能力。", 0.84),
                new Rule("DATA003", "sensitive_report_export", Severity.HIGH,
                        "(csv|xlsx|excel|json|har|trace|截图|screenshot|allure|attachment).*(身份证|银行卡|手机号|token|cookie|accountNo|cardNo)",
                        "报告、附件或导出文件可能包含敏感字段",
                        "测试报告和附件应自动脱敏，HAR/trace/screenshot 需要按敏感材料管理。", 0.82),
                new Rule("ENV001", "environment_switch_to_prod", Severity.CRITICAL,
                        "(ENV|PROFILE|SPRING_PROFILES_ACTIVE|NODE_ENV|targetEnv|环境)\\s*=\\s*(prod|production|生产)",
                        "疑似将执行环境切换到生产",
                        "Skill 应默认指向隔离测试环境，生产环境切换必须由外部审批流程控制。", 0.9),
                new Rule("ENV002", "host_proxy_mutation", Severity.HIGH,
                        "(hosts|/etc/hosts|C:\\\\Windows\\\\System32\\\\drivers\\\\etc\\\\hosts|HTTP_PROXY|HTTPS_PROXY|NO_PROXY|代理|证书信任|truststore|keystore)",
                        "可能修改主机、代理或证书信任配置",
                        "测试 Skill 不应静默修改网络解析、代理或证书信任链；需要可回滚的变更说明。", 0.76),
                new Rule("ENV003", "jump_host_or_vpn", Severity.HIGH,
                        "(堡垒机|跳板机|vpn|bastion|jumpserver|ssh\\s+.*@|kubectl\\s+config|kubeconfig)",
                        "疑似访问堡垒机、VPN、集群或跳板机配置",
                        "访问受控内网资源必须依赖企业准入和审计，不应由 Skill 自动化绕过。", 0.78),
                new Rule("NORM-ACCESS001", "norm_access_control", Severity.HIGH,
                        "(水平越权|垂直越权|未授权|越权|bypass|idor|任意用户|任意账号|userId|projectId|orderId).*(无鉴权|未校验|前端校验|直接查询|可篡改)",
                        "行内规范：疑似访问控制、水平越权或垂直越权风险",
                        "所有接口必须服务端统一鉴权，并按用户、角色、资源属性校验数据权限。", 0.75),
                new Rule("NORM-ACCESS002", "norm_business_flow_bypass", Severity.HIGH,
                        "(跳过|绕过|乱序|重复提交|直接调用).*(流程|步骤|审批|交易|支付|退款|放款)",
                        "行内规范：疑似业务流程绕过或关键步骤缺失",
                        "多步骤业务应服务端校验前序步骤、状态机、幂等标记和重复提交保护。", 0.76),
                new Rule("DB001", "unsafe_sql_without_where", Severity.CRITICAL,
                        "\\bdelete\\s+from\\s+\\w+\\b(?!.*\\bwhere\\b)|\\bupdate\\s+\\w+\\s+set\\b(?!.*\\bwhere\\b)",
                        "疑似无 where 条件的 delete/update",
                        "清数和造数脚本必须限定测试数据范围，并具备事务回滚和审计记录。", 0.86),
                new Rule("DB002", "financial_state_mutation", Severity.CRITICAL,
                        "(balance|amount|limit|credit|rate|status|freeze|余额|金额|额度|授信|利率|状态|冻结).{0,40}(update|set|修改|置为|变更)",
                        "疑似修改账务、额度或客户状态字段",
                        "账务类数据变更必须限制在隔离测试库，并由最小权限账号执行。", 0.86),
                new Rule("DB003", "transaction_safety_missing", Severity.HIGH,
                        "(autoCommit\\s*=\\s*true|setAutoCommit\\(true\\)|commit\\(\\)).{0,80}(delete|update|insert|truncate|drop)",
                        "数据库变更可能缺少事务保护或回滚策略",
                        "测试造数/清数脚本应默认开启事务、支持回滚，并输出影响行数。", 0.78),
                new Rule("APISEC001", "bruteforce_or_otp_attack", Severity.HIGH,
                        "(爆破|bruteforce|brute force|字典|wordlist|password spraying|验证码|otp).*(login|登录|密码|password|mfa|短信)",
                        "疑似批量爆破登录、密码、验证码或 OTP",
                        "鉴权安全测试必须限制测试账号、速率、次数和环境，避免影响真实认证服务。", 0.82),
                new Rule("APISEC002", "fuzz_without_limit", Severity.HIGH,
                        "(fuzz|payloads?|wordlist|遍历接口|批量请求|参数篡改).*(while\\s+true|for\\s*\\(|并发|threads?|qps|rate)",
                        "接口安全测试可能缺少速率或范围限制",
                        "Fuzz、越权和参数篡改测试必须声明目标范围、QPS、账号和回滚策略。", 0.8),
                new Rule("APISEC003", "financial_replay_risk", Severity.CRITICAL,
                        "(重放|replay|重复提交|幂等|idempotent|转账|支付|放款|撤销|退款).*(amount|金额|account|账户|order|订单|transaction|交易)",
                        "疑似交易重放、重复支付或金额篡改测试",
                        "交易类安全测试必须限定沙箱环境、测试账户和幂等保护，禁止打到真实链路。", 0.88),
                new Rule("APISEC004", "security_payload_to_url", Severity.MEDIUM,
                        "('|\\\"|%27).*(or\\s+1=1|<script|\\.\\./|;\\s*(cat|id|whoami))|sqlmap|xss|ssrf|xxe",
                        "存在注入、XSS、SSRF、目录穿越等安全测试载荷",
                        "安全载荷只能发送到授权测试环境，并应记录测试范围和审批依据。", 0.7),
                new Rule("NORM-INPUT001", "norm_input_validation", Severity.MEDIUM,
                        "(前端校验|客户端校验|hidden|header|cookie|url参数|request[_-]?params).*(未校验|无校验|可篡改|任意)",
                        "行内规范：外部输入可能缺少服务端校验",
                        "所有外部输入应在服务端按类型、长度、范围和白名单规则校验。", 0.68),
                new Rule("NORM-INPUT002", "norm_output_encoding", Severity.MEDIUM,
                        "(html|js|javascript|url|css|输出|展示).*(未编码|无编码|原样输出|raw|innerHTML)",
                        "行内规范：输出可能缺少上下文编码",
                        "按 HTML、URL、JavaScript、CSS 上下文分别编码，避免 XSS 和注入风险。", 0.66),
                new Rule("NORM-DATA001", "norm_data_masking", Severity.HIGH,
                        "(伪脱敏|接口返回明文|页面脱敏.*接口.*明文|脱敏.*不一致|敏感数据.*明文)",
                        "行内规范：疑似敏感数据脱敏或明文保护不足",
                        "展示、接口响应、报告和导出文件应保持一致脱敏；身份鉴别类数据必须加密存储。", 0.82),
                new Rule("NORM-DATA002", "norm_data_transfer_storage", Severity.HIGH,
                        "(http://|明文传输|明文存储|md5|sha1|des|base64).*(密码|人脸|指纹|身份证|银行卡|手机号|token|cookie)",
                        "行内规范：敏感数据传输、存储或算法使用可能不合规",
                        "敏感数据应使用安全协议和合规加密算法；高安全场景禁止 MD5、SHA1、DES。", 0.82),
                new Rule("NORM-FILE001", "norm_file_upload_security", Severity.HIGH,
                        "(fileUpload|upload|上传).*(未限制|任意|无校验|不校验|可执行|web目录|原文件名)",
                        "行内规范：文件上传可能缺少类型、大小、隔离或执行权限控制",
                        "服务端应校验类型、大小和文件头，重命名后存放隔离目录并关闭执行权限。", 0.78),
                new Rule("NORM-FILE002", "norm_file_download_security", Severity.HIGH,
                        "(download|下载|filepath|filename|path).*(\\.\\./|路径遍历|任意文件|目录浏览|directory listing)",
                        "行内规范：文件下载或目录浏览可能存在路径遍历风险",
                        "下载必须做路径白名单与权限校验，拒绝 ../ 等非法字符并关闭涉敏目录浏览。", 0.82),
                new Rule("NORM-API001", "norm_api_rate_idempotent", Severity.MEDIUM,
                        "(api|接口).*(无限频|无频率|不限次数|无幂等|无审计|最小响应|过度返回)",
                        "行内规范：API 可能缺少限频、幂等、审计或最小响应控制",
                        "API 应具备认证授权、限频、幂等、最小参数/响应和统一审计日志。", 0.68),
                new Rule("NORM-CLIENT001", "norm_client_security", Severity.MEDIUM,
                        "(root|越狱|模拟器|hook|frida|xposed|完整性|混淆|加固).*(未检测|无检测|未校验|关闭|禁用)",
                        "行内规范：客户端运行环境、完整性或代码保护可能不足",
                        "客户端应检测 Root/越狱/模拟器和攻击工具，校验完整性并保护认证信息。", 0.66),
                new Rule("NORM-TRADE001", "norm_transaction_security", Severity.CRITICAL,
                        "(支付|转账|退款|放款|审批|交易).*(无唯一|无交易号|无幂等|无二次认证|金额可改|币种可改|重复提交)",
                        "行内规范：交易场景可能缺少防重放、幂等、金额校验或二次认证",
                        "交易类操作必须使用唯一交易号、限频、MFA、服务端金额币种校验和幂等控制。", 0.86),
                new Rule("NORM-LOG001", "norm_log_audit", Severity.MEDIUM,
                        "(日志|log|audit).*(未记录|无审计|可篡改|敏感明文|密码|session|token|cookie)",
                        "行内规范：日志审计可能不足或存在敏感信息泄露",
                        "关键操作应接入统一日志平台并防篡改；日志不得记录密码、会话 ID 或敏感明文。", 0.72),
                new Rule("AUTO001", "business_action_click", Severity.HIGH,
                        "(click|点击|tap|press).{0,60}(提交|确认|转账|支付|放款|审批|退款|撤销|submit|confirm|pay|approve|refund)",
                        "自动化脚本可能触发真实业务动作",
                        "UI 自动化触发资金或审批动作前必须使用沙箱账号，并加入人工确认或环境保护。", 0.8),
                new Rule("AUTO002", "artifact_outside_workspace", Severity.MEDIUM,
                        "(screenshot|trace|har|download|截图|下载|报告).*(Desktop|Downloads|/tmp|C:\\\\Users|公共目录|共享目录)",
                        "测试产物可能写入非项目受控目录",
                        "测试产物应保存到当前工作区的受控报告目录，避免泄露到公共或个人目录。", 0.72),
                new Rule("CI001", "ci_secret_print", Severity.CRITICAL,
                        "((^|\\s)(printenv|env|set)\\s+|Get-ChildItem\\s+Env:|echo\\s+\\$).*(SECRET|TOKEN|PASSWORD|COOKIE|KEY|ACCESS)",
                        "CI 中可能打印敏感环境变量",
                        "流水线日志必须禁止输出 secrets、token、cookie、密钥和完整环境变量。", 0.88),
                new Rule("CI002", "ci_gate_bypass", Severity.HIGH,
                        "(skip tests|skipTests|maven\\.test\\.skip|--skip|跳过测试|跳过扫描|disable.*scan|quality gate|sonar.*skip)",
                        "可能跳过测试、安全扫描或质量门禁",
                        "Skill 不应静默关闭团队质量门禁；临时跳过必须有审批和恢复说明。", 0.78),
                new Rule("CI003", "unsafe_dependency_install", Severity.MEDIUM,
                        "(npm|pnpm|yarn|pip|mvn|gradle).*(latest|SNAPSHOT|--legacy-peer-deps|--ignore-scripts|--no-verify)",
                        "依赖安装可能不可复现或绕过安全机制",
                        "依赖版本应锁定，避免 latest/SNAPSHOT，并谨慎使用绕过校验参数。", 0.7),
                new Rule("REPORT001", "external_notification", Severity.HIGH,
                        "(webhook|企业微信|飞书|钉钉|slack|email|smtp|mail).*(report|报告|allure|失败|缺陷|bug|token|cookie)",
                        "可能把测试报告或敏感信息发送到外部通知渠道",
                        "报告推送应限定企业受控渠道，并对请求、响应、截图和附件做脱敏。", 0.78),
                new Rule("REPORT002", "defect_leakage", Severity.HIGH,
                        "(jira|禅道|tapd|bug|defect|缺陷).*(request|response|header|cookie|token|身份证|银行卡|手机号)",
                        "缺陷流转内容可能携带敏感请求、响应或客户信息",
                        "自动创建缺陷前应过滤请求头、Cookie、Token 和客户敏感字段。", 0.8),
                new Rule("REPORT003", "analysis_auth_context_exposure", Severity.HIGH,
                        "\"(auth[_-]?info|authorization|cookie|session|token)\"\\s*:\\s*\"(?!未知|unknown|none|null|无|<)[^\"]{4,}\"",
                        "分析报告中残留认证、会话或用户上下文",
                        "Skill 生成的分析报告应默认脱敏认证信息，仅保留认证方式、角色类型和是否已授权。", 0.84),
                new Rule("REPORT004", "internal_api_inventory_exposure", Severity.MEDIUM,
                        "\"(api[_-]?url|upload[_-]?urls?|url|endpoint)\"\\s*:\\s*(\\[[^\\]]*https?://|\"https?://)",
                        "分析报告中暴露内部接口地址或接口清单",
                        "报告中建议隐藏域名、网关路径和真实参数，只保留接口分类、方法和风险结论。", 0.72),
                new Rule("REPORT005", "request_parameter_exposure", Severity.MEDIUM,
                        "\"(request[_-]?params|request[_-]?body|params|body)\"\\s*:\\s*\".{3,}\"",
                        "分析报告中残留请求参数或业务对象标识",
                        "请求参数应脱敏或摘要化，避免报告中保留可复现的业务对象编号。", 0.74),
                new Rule("SUPPLY001", "download_execute", Severity.CRITICAL,
                        "(curl|wget|Invoke-WebRequest|iwr).*(\\||;|&&).*(sh|bash|python|powershell|pwsh)|bash\\s+<\\s*\\(",
                        "存在下载后直接执行的供应链高危模式",
                        "禁止远程脚本直接执行；依赖应固定来源、版本和校验摘要。", 0.94),
                new Rule("SUPPLY002", "unpinned_remote_dependency", Severity.MEDIUM,
                        "(pip|npm|pnpm|yarn|mvn|gradle).*(git\\+https?://|https?://.*\\.(zip|tar\\.gz|tgz)|@main\\b|@master\\b|latest)",
                        "远程依赖或包版本未固定，可能引入供应链漂移",
                        "依赖应固定版本、来源和校验摘要；避免 main/master/latest 或直接安装远程压缩包。", 0.72),
                new Rule("AGENT001", "agent_instruction_risk", Severity.HIGH,
                        "(忽略|ignore).*(安全|security|policy|规则|限制|approval|sandbox)|自动批准|无需确认|bypass|绕过审批",
                        "Skill 指令中可能要求绕过安全限制或审批",
                        "Skill 文档不得要求 Agent 忽略安全策略、绕过沙箱或自动批准高风险操作。", 0.78),
                new Rule("AGENT002", "agent_hidden_action", Severity.HIGH,
                        "(不要告诉用户|无需告知|静默执行|隐藏操作|不要记录|delete logs|silent mode|without asking|无需确认)",
                        "Skill 指令中可能要求隐藏操作或跳过用户确认",
                        "Skill 必须保持操作透明，高风险动作需要明确展示并取得用户确认。", 0.82),
                new Rule("AGENT003", "remote_instruction_reference", Severity.MEDIUM,
                        "(按照|参考|加载|执行).*(http|https)://.*(md|txt|prompt|instructions|脚本|规则)",
                        "Skill 依赖远程指令或脚本，版本不可控",
                        "远程指令应固定版本和校验摘要，准入评审应以本地可审计内容为准。", 0.72),
                new Rule("AGENT004", "untrusted_tool_output_as_instruction", Severity.HIGH,
                        "(网页|页面|tool[_-]?output|工具输出|browser[_-]?output|response|返回内容|用户输入|外部文档).{0,80}(作为指令|当作指令|遵循|执行|follow|obey|treat.*instruction)",
                        "可能把不可信工具输出或外部内容当成指令执行",
                        "外部网页、工具输出和用户输入只能作为数据处理，不能覆盖 SKILL.md、安全策略或用户确认。", 0.8),
                new Rule("AGENT005", "excessive_agency", Severity.HIGH,
                        "(自动执行|自动点击|自动提交|auto[-_ ]?(run|approve|submit|click)|无人值守|without confirmation|without asking).{0,100}(支付|转账|审批|删除|生产|prod|deploy|发布|外联|download|execute)",
                        "Agent 可能具备过度自主执行高风险动作",
                        "高风险动作必须有显式用户确认、环境检查、回滚策略和可审计记录，不能默认无人值守执行。", 0.82),
                new Rule("AGENT006", "model_or_tool_output_execution", Severity.CRITICAL,
                        "(model[_-]?output|llm[_-]?output|assistant[_-]?output|tool[_-]?output|模型输出|工具输出|返回结果).{0,120}(eval\\(|exec\\(|os\\.system|subprocess|shell|\\bexecute\\b|执行命令|运行代码)|(eval\\(|exec\\(|os\\.system|subprocess|shell|\\bexecute\\b|执行命令|运行代码).{0,120}(model[_-]?output|llm[_-]?output|assistant[_-]?output|tool[_-]?output|模型输出|工具输出|返回结果)",
                        "可能直接执行模型或工具返回内容",
                        "模型/工具输出必须当作不可信数据，禁止直接 eval、exec、shell 执行；如需执行必须经过白名单解析和人工确认。", 0.88),
                new Rule("META001", "skill_quality", Severity.LOW,
                        "TODO|FIXME|待补充|临时方案",
                        "Skill 文档或脚本仍包含未完成标记",
                        "发布前补齐说明、限制条件和验证方式。", 0.55)
        );
    }
}
